### ISSUE TITLE
Proposal for removal of "auto-recovery" alarm setting

### ISSUE THREAD

**Issue by sasikeda** [IBM/ibm-spectrum-scale-cloud-install#15]

**Comment by gandhisanjayv** [comment]
automatic recovery of an EC2 instance when a system status check of the underlying hardware fails. The instance will be rebooted (on new hardware if necessary) but will retain its Instance Id, IP Address, Elastic IP Addresses, EBS Volume attachments, and other configuration details. In order for the recovery to be complete, you’ll need to make sure that the instance automatically starts up any services or applications as part of its initialization process.

So no additional steps required from Spectrum Scale perspective.  Spectrum Scale node will be evicted from the cluster due to failure and it will join back after instance is rebooted after auto-recovery,
