### ISSUE TITLE
"Termination protection = False"  in instances created by stack

### ISSUE THREAD

**Issue by nilbante** [IBM/ibm-spectrum-scale-cloud-install#96]
We deployed stacks through terraform deploy and checked termination protection value . Its false which indicates this instance can be terminated using the console, API, or CLI until termination protection is disabled. 
In AWS 1.2, this value was true. Check if there is any special reason for having as false.

**Comment by nilbante** [comment]
fyi @gandhisanjayv

**Comment by sasikeda** [comment]
The reason for not using "disable_api_termination" is because the resource will no longer be accessed by API and that causes terraform to fail during the scenario of expansion, contraction and destroy. once has to use aws cli to enable api termination and then has to use terraform for lifecycle operations. To avoid multiple api cals, it has been disabled. however one can use it by providing it in the user json input.
