### ISSUE TITLE
"Delete on termination = True"  for ebs volume created in storage node

### ISSUE THREAD

**Issue by nilbante** [IBM/ibm-spectrum-scale-cloud-install#98]
Fetched below data from the storage node

```
EBS IDvol-03c7851118d638776
--
Root device typeEBS
Attachment time2020-05-19T00:41:55.000Z
Block device statusattached
Delete on termination True
```
With the current default setting, the volume will be deleted with storage node deletion.

With a setting as false, it will provide protection against accidental deletion. 
If required, customers can delete it via gui. It will be good if we handle it through tear down. First, change flag and delete it so volume will be cleanup with storage node deletion.

**Comment by nilbante** [comment]
fyi @gandhisanjayv

**Comment by sasikeda** [comment]
I agree with the concern and thanks for reporting.

Currently, this option is enabled in terraform code. We are not exercising it, for the reason even if we have the EBS volumes, we cannot reconstruct back easily. In order to allow it, we should be supporting `mminmportfs`, `mmexportfs` to backup the NSD layout and likewise document the reconstruction steps (so that the detached EBS volume will be useful). In the current scope, we are not containing it (will put this to the next release items).

For now, it will be documented, that once the storage instances are terminated, EBS volumes attachned to them will be deleted.
